### PR TITLE
Enable clickable buffers under Neovim

### PR DESCRIPTION
**Pull request by brglng**
1. Make buffer labels clickable by using the `tablineat` feature.
2. Add a new option `g:lightline#bufferline#clickable` to turn on/off this feature. The default value is `0`.

### CODE REVIEW

**Comment by mengelbrecht** [comment]
This is a nice feature.
However, it seems to break the "more-buffers" functionality where buffers are hidden if there is not enough screen space to display them.
The length of the buffer names is used to calculate the amount of buffers that can be displayed. With your change the string `@lightline#bufferline#_click_handler@` is counted against the buffer name length but is not actually displayed. Therefore the amount of buffers displayed is not correct.

**Comment by brglng** [comment]
@mengelbrecht Thank you for pointing that out! Let me try to fix that issue.

**Comment by brglng** [comment]
Hi @mengelbrecht , I have fixed the incorrect calculation of the lengths of buffer names. Could you please take a look?

**Comment by mengelbrecht** [comment]
Nice work! Thanks

**Comment by brglng** [comment]
Thanks.

There are still some problems I am thinking of:

1. Make the `...` also clickable, so that we can switch the bufferline pages
2. Make the bufferline able to show an incomplete buffer label, so that the bufferline's view won't change when switching buffers in the same bufferline page

These are complex and not easy to implement though. Maybe I will do some trying in the future.

**Pull request merged**
